# Generated by Django 3.2.23 on 2024-02-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240207_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_spam',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
